/*
 * Toolbox.java
 *
 * Created on Apr 23, 2011, 6:14:46 PM
 */
package stormgate.editor.ui.forms.tool;

import stormgate.editor.data.EditorData;
import stormgate.editor.tool.ToolInterface;

/**
 *
 * @author David
 */
public class Toolbox extends javax.swing.JPanel
{

	private EditorData data;

	/** Creates new form Toolbox */
	public Toolbox()
	{
		initComponents();
	}

	public void setData(EditorData data)
	{
		this.data = data;
		data.setToolbox(this);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(180, 24));
        setMinimumSize(new java.awt.Dimension(180, 24));
        setPreferredSize(new java.awt.Dimension(180, 24));

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stormgate/editor/ui/forms/icons/tile.png"))); // NOI18N
        jToggleButton2.setToolTipText("Tile Tool");
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton2.setFocusPainted(false);
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setMaximumSize(new java.awt.Dimension(24, 24));
        jToggleButton2.setMinimumSize(new java.awt.Dimension(24, 24));
        jToggleButton2.setPreferredSize(new java.awt.Dimension(24, 24));
        jToggleButton2.setRolloverEnabled(false);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stormgate/editor/ui/forms/icons/background.png"))); // NOI18N
        jToggleButton3.setToolTipText("Background Tool");
        jToggleButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton3.setFocusPainted(false);
        jToggleButton3.setFocusable(false);
        jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton3.setMaximumSize(new java.awt.Dimension(24, 24));
        jToggleButton3.setMinimumSize(new java.awt.Dimension(24, 24));
        jToggleButton3.setPreferredSize(new java.awt.Dimension(24, 24));
        jToggleButton3.setRolloverEnabled(false);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stormgate/editor/ui/forms/icons/palette.png"))); // NOI18N
        jToggleButton4.setSelected(true);
        jToggleButton4.setToolTipText("Graphics Tool");
        jToggleButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton4.setFocusPainted(false);
        jToggleButton4.setFocusable(false);
        jToggleButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton4.setMaximumSize(new java.awt.Dimension(24, 24));
        jToggleButton4.setMinimumSize(new java.awt.Dimension(24, 24));
        jToggleButton4.setPreferredSize(new java.awt.Dimension(24, 24));
        jToggleButton4.setRolloverEnabled(false);
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stormgate/editor/ui/forms/icons/zone.png"))); // NOI18N
        jToggleButton5.setToolTipText("Zone Tool");
        jToggleButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton5.setFocusPainted(false);
        jToggleButton5.setFocusable(false);
        jToggleButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton5.setMaximumSize(new java.awt.Dimension(24, 24));
        jToggleButton5.setMinimumSize(new java.awt.Dimension(24, 24));
        jToggleButton5.setPreferredSize(new java.awt.Dimension(24, 24));
        jToggleButton5.setRolloverEnabled(false);
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton6);
        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stormgate/editor/ui/forms/icons/entity.png"))); // NOI18N
        jToggleButton6.setToolTipText("Entity Tool");
        jToggleButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton6.setFocusPainted(false);
        jToggleButton6.setFocusable(false);
        jToggleButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton6.setMaximumSize(new java.awt.Dimension(24, 24));
        jToggleButton6.setMinimumSize(new java.awt.Dimension(24, 24));
        jToggleButton6.setPreferredSize(new java.awt.Dimension(24, 24));
        jToggleButton6.setRolloverEnabled(false);
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

	private void changeTool(ToolInterface tool)
	{
		data.changeTool(tool);
	}

	private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton3ActionPerformed
	{//GEN-HEADEREND:event_jToggleButton3ActionPerformed
		//Background Tool
		changeTool(data.backgroundTool);
	}//GEN-LAST:event_jToggleButton3ActionPerformed

	private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton2ActionPerformed
	{//GEN-HEADEREND:event_jToggleButton2ActionPerformed
		//Tile Tool
		changeTool(data.tileTool);
	}//GEN-LAST:event_jToggleButton2ActionPerformed

	private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton4ActionPerformed
	{//GEN-HEADEREND:event_jToggleButton4ActionPerformed
		//Graphic Tool
		changeTool(data.graphicTool);
	}//GEN-LAST:event_jToggleButton4ActionPerformed

	private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton5ActionPerformed
	{//GEN-HEADEREND:event_jToggleButton5ActionPerformed
		//Zone Tool
		changeTool(data.zoneTool);
	}//GEN-LAST:event_jToggleButton5ActionPerformed

	private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton6ActionPerformed
	{//GEN-HEADEREND:event_jToggleButton6ActionPerformed
		//Entity Tool
		changeTool(data.entityTool);
	}//GEN-LAST:event_jToggleButton6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    // End of variables declaration//GEN-END:variables

	public void updateTool()
	{
		ToolInterface tool = data.getTool();

		if(tool == data.tileTool){
			jToggleButton2.setSelected(true);
		}else if(tool == data.graphicTool){
			jToggleButton4.setSelected(true);
		}else if(tool == data.zoneTool){
			jToggleButton5.setSelected(true);
		}else if(tool == data.backgroundTool){
			jToggleButton3.setSelected(true);
		}else if(tool == data.entityTool){
			jToggleButton6.setSelected(true);
		}
	}
}
