/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TileToolPanel.java
 *
 * Created on Apr 20, 2011, 9:33:03 PM
 */

package stormgate.editor.tool.panel;

import stormgate.image.LibraryResource;

/**
 *
 * @author David
 */
public class BackgroundToolPanel extends ToolPanel {

    /** Creates new form TileToolPanel */
    public BackgroundToolPanel() {
        initComponents();
    }

	public void setGraphic(LibraryResource resource)
	{
		graphicViewer1.setResource(resource);
		repaint();
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphicViewer1 = new stormgate.editor.tool.panel.GraphicViewer();

        setAutoscrolls(true);

        javax.swing.GroupLayout graphicViewer1Layout = new javax.swing.GroupLayout(graphicViewer1);
        graphicViewer1.setLayout(graphicViewer1Layout);
        graphicViewer1Layout.setHorizontalGroup(
            graphicViewer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        graphicViewer1Layout.setVerticalGroup(
            graphicViewer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphicViewer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphicViewer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private stormgate.editor.tool.panel.GraphicViewer graphicViewer1;
    // End of variables declaration//GEN-END:variables

}
