/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LibraryPathDialog.java
 *
 * Created on Apr 1, 2011, 10:25:21 PM
 */

package stormgate.editor.ui.forms.fileDialog;

import java.awt.Frame;
import java.io.File;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreePath;
import stormgate.editor.ui.forms.browser.LibraryViewer;

/**
 *
 * @author David
 */
public class LibraryPathDialog extends javax.swing.JDialog {

	private MutableTreeNode root;
	private TreePath selectedPath;
	private LibraryPathAction action;
	
    /** Creates new form LibraryPathDialog */
    public LibraryPathDialog(LibraryPathAction action) {
		super(new Frame(), true);
		this.action = action;
		root = new DefaultMutableTreeNode("root");
		listDirectory();
        initComponents();
		DefaultTreeCellRenderer label = new DefaultTreeCellRenderer();
		label.setLeafIcon(label.getOpenIcon());
		jTree1.setCellRenderer(label);
    }

	private void listDirectory(){
		//root = new DefaultMutableTreeNode("WTF!");
		listDirectory(root, new File(LibraryViewer.mainDirectory));
		//revalidate();
	}

	private void listDirectory(MutableTreeNode node, File dir){
		String[] children = dir.list();
		if (children != null) {
			for (int i=0; i<children.length; i++) {
				// Get filename of file or directory
				String filename = children[i];
				File f = new File(dir.getPath() + "/" + filename);
				if(f.isDirectory()) {
					DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(filename);
					node.insert(newNode, 0);
					listDirectory(newNode, f);
				}
			}
		}
	}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree(root);
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Directory");
        setAlwaysOnTop(true);

        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("Path to directory");

        jButton2.setText("Select");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	public String getStringPath(TreePath path){
		Object object = path.getLastPathComponent();
		if(object == root){
			return LibraryViewer.mainDirectory;
		}
		String lastPath = object.toString();
		TreePath parent = path.getParentPath();
		if(parent != null){
			lastPath = getStringPath(parent) + "/" + lastPath;
		}
		return lastPath;
	}

	private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
		selectedPath = evt.getPath();
		
		jTextField1.setText(getStringPath(selectedPath));
	}//GEN-LAST:event_jTree1ValueChanged

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		this.dispose();
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		if(action.select(getStringPath(selectedPath))){
			this.dispose();
		}
	}//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

}
