/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MapProperty.java
 *
 * Created on Sep 20, 2011, 3:43:12 PM
 */
package stormgate.editor.ui.forms.dialog;

import java.awt.Frame;
import java.io.File;
import javax.swing.JOptionPane;
import stormgate.data.Tile;
import stormgate.editor.data.EditorData;
import stormgate.editor.ui.forms.browser.LibraryViewer;
import stormgate.editor.ui.forms.fileDialog.AWTFileDialog;
import stormgate.map.Map;

/**
 *
 * @author David
 */
public class MapProperty extends javax.swing.JDialog
{

	EditorData data;
	File libraryDirectory;
	File defaultTile;
	private AWTFileDialog dialog;

	/** Creates new form MapProperty */
	public MapProperty(java.awt.Frame parent, boolean modal)
	{
		super(parent, modal);
		initComponents();

		dialog = new AWTFileDialog();
	}

	@Override
	public void setVisible(boolean v){

		defaultTile = new File(Tile.defaultTile);
		libraryDirectory = new File(LibraryViewer.mainDirectory);
		Map map = data.getMap();
		jTextField1.setText(map.getMapName());
		jLabel3.setText(reformatText(defaultTile.toString()));
		jLabel7.setText(reformatText(libraryDirectory.toString()));

		super.setVisible(v);
	}

	public void setData(EditorData data)
	{
		this.data = data;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel1.setText("Map Name");

        jLabel4.setText("Default Tile");

        jLabel6.setText("Library Directory");

        jLabel7.setText("map");

        jLabel3.setText("tile1.png");

        jButton3.setText("Browse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jButton3))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
	{//GEN-HEADEREND:event_jButton4ActionPerformed
		//SAVE
		File parent = libraryDirectory;
		File child = defaultTile;
		try {
			child = child.getCanonicalFile();
			parent = libraryDirectory.getCanonicalFile();
		} catch (Exception e) {
		}

		//Tile must be within the library
		if (isChildofFile(parent, child)) {
			Map map = data.getMap();
			map.setMapName(jTextField1.getText());
			//LibraryViewer.mainDirectory = libraryDirectory.toString();
			Tile.defaultTile = defaultTile.toString();
		} else {
			JOptionPane.showMessageDialog(new Frame(), "The default tile must be a child of the library");
			return;
		}

		data.refreshLibrary();
		data.refresh();
		this.setVisible(false);
	}//GEN-LAST:event_jButton4ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
	{//GEN-HEADEREND:event_jButton1ActionPerformed
		//CANCEL
		this.setVisible(false);
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
	{//GEN-HEADEREND:event_jButton3ActionPerformed
		//DEFAULT TILE
		String filePath = dialog.openFile("Default Tile", defaultTile.getParent(), "*.png");
		if (filePath != null) {
			File path = new File(".");
			File parent = libraryDirectory;
			File child = new File(filePath);
			try {
				path = path.getCanonicalFile();
				child = child.getCanonicalFile();
				parent = libraryDirectory.getCanonicalFile();
			} catch (Exception e) {
			}

			//Tile must be within the library
			if (isChildofFile(parent, child)) {
				defaultTile = new File(unfilter(filePath, path.getAbsolutePath() + "\\"));
			} else {
				JOptionPane.showMessageDialog(new Frame(), "The default tile must be a child of the library");
			}
		}
		jLabel3.setText(reformatText(defaultTile.toString()));
	}//GEN-LAST:event_jButton3ActionPerformed

	private boolean isChildofFile(File parent, File child)
	{
		if (child == null) {
			return false;
		}
		if (parent.equals(child)) {
			return true;
		}

		return isChildofFile(parent, child.getParentFile());
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

	private String unfilter(String str, String path)
	{
		if (str.length() > 0) {
			path = path.replaceAll("(\\\\)", "\\\\\\\\\\\\\\\\");
			str = str.replaceAll("(\\\\)", "\\\\\\\\");
			str = str.replaceAll(path, "");
			return str.replaceAll("(\\\\\\\\)", "\\\\");
		}
		return str;
	}

	public String reformatText(String str)
	{
		if (str.length() > 20) {
			str = ".." + str.substring(str.length() - 20);
		}
		return str;
	}
}
